version: "3.8"

services:
    #Database Server
    database:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - network
    #PHP Service
    php:
        build:
            context: .
            target: php
            dockerfile: Dockerfile
            args:
                APP_ENV: ${APP_ENV}
        environment:
            APP_ENV: ${APP_ENV}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_DATABASE: ${DB_DATABASE}
            DB_HOST: ${DB_HOST}
            CONTAINER_ROLE: app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - database
        networks:
            - network
    #Web Server
    webserver:
        image: nginx:1.23
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - network

volumes:
    dbdata: ~
networks:
    network:


